### AL3 AUTHORS
GET  http://localhost:3000/api/products/

### SINGLE AUTHOR
GET  http://localhost:3000/api/products/2

### POST REQUEST TO AUTHORS
POST http://localhost:3000/api/products/
Content-Type: application/json

{
    "name": "Ely",
    "description":"She's a beauty mother" ,
    "sku":"1234",
    "price":100
}

### PUT REQUEST TO AUTHORS
POST http://localhost:3000/api/products/2?_method=PUT
Content-Type: application/json

{
    "name": "Bottle of wter",
    "description": "It's just a bottle of water"
}

### DELETE REQUEST TO AUTHORS
DELETE http://localhost:3000/api/products/2