### ALL AUTHORS
GET  http://localhost:8000/api/products/

### SINGLE AUTHOR
GET  http://localhost:8000/api/products/2

### POST REQUEST TO AUTHORS
POST http://localhost:8000/api/products/
Content-Type: application/json

{
    "name": "Bottle of water",
    "description": "It's just a bottle of water",
    "sku":"1234"
}

### PUT REQUEST TO AUTHORS
POST http://localhost:8000/api/products/2?_method=PUT
Content-Type: application/json

{
    "name": "Bottle of wter",
    "description": "It's just a bottle of water"
}

### DELETE REQUEST TO AUTHORS
DELETE http://localhost:8000/api/products/2